import type { Knex } from 'knex';

const TABLE = 'df_housing_nat_2024';

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable(TABLE, (table) => {
    table.string('idlocal', 12);
    table.string('idbat', 16);
    table.string('idpar', 14);
    table.string('idtup');
    table.string('idsec', 10);
    table.string('idvoie', 9);
    table.string('idprocpte', 11);
    table.string('idcom', 5);
    table.string('idcomtxt');
    table.string('ccodep', 2);
    table.string('ccodir', 1);
    table.string('ccocom', 3);
    table.string('invar', 10);
    table.string('ccopre', 3);
    table.string('ccosec', 2);
    table.string('dnupla', 4);
    table.string('dnubat', 2);
    table.string('descc', 2);
    table.string('dniv', 2);
    table.string('dpor', 5);
    table.string('ccoriv', 4);
    table.string('ccovoi', 5);
    table.string('dnvoiri', 4);
    table.string('dindic', 1);
    table.string('ccocif', 4);
    table.string('dvoilib');
    table.string('cleinvar', 1);
    table.string('assieft');
    table.string('ccpper', 3);
    table.string('codique');
    table.string('gpdl', 1);
    table.string('ctpdl', 5);
    table.string('dnupro', 6);
    table.string('jdatat', 8);
    table.string('jdatatv', 8);
    table.string('jdatatan', 4);
    table.string('dnufnl', 6);
    table.string('ccoeva', 1);
    table.string('ccoevatxt');
    table.string('dteloc', 1);
    table.string('dteloctxt');
    table.string('typeloc');
    table.boolean('logh');
    table.boolean('loghmais');
    table.boolean('loghappt');
    table.string('gtauom', 2);
    table.string('dcomrd', 3);
    table.string('ccoplc', 1);
    table.string('ccoplctxt');
    table.string('cconlc', 2);
    table.string('cconlctxt');
    table.integer('dvltrt');
    table.string('cc48lc', 2);
    table.integer('dloy48a');
    table.string('top48a', 1);
    table.string('dnatlc', 1);
    table.string('ccthp');
    table.string('rppo_rs');
    table.string('typeact', 4);
    table.string('loghvac', 1);
    table.boolean('loghvac2a');
    table.boolean('loghvac5a');
    table.string('loghvacdeb', 5);
    table.string('cchpr', 1);
    table.string('jannat', 4);
    table.string('dnbniv', 2);
    table.integer('nbetagemax');
    table.integer('nbnivssol');
    table.string('hlmsem', 1);
    table.string('loghlls', 15);
    table.string('postel', 1);
    table.string('dnatcg', 2);
    table.string('jdatcgl', 8);
    table.integer('fburx');
    table.string('gimtom', 1);
    table.string('cbtabt', 2);
    table.string('jdbabt', 4);
    table.string('jrtabt', 4);
    table.string('cconac', 5);
    table.string('cconactxt', 129);
    table.string('toprev', 1);
    table.integer('ccoifp');
    table.string('jannath');
    table.integer('janbilmin');
    table.integer('npevph');
    table.integer('stoth');
    table.integer('stotdsueic');
    table.integer('npevd');
    table.integer('stotd');
    table.integer('npevp');
    table.integer('sprincp');
    table.integer('ssecp');
    table.integer('ssecncp');
    table.integer('sparkp');
    table.integer('sparkncp');
    table.integer('npevtot');
    table.integer('slocal');
    table.integer('npiece_soc');
    table.integer('npiece_ff');
    table.integer('npiece_i');
    table.integer('npiece_p2');
    table.integer('nbannexe');
    table.integer('nbgarpark');
    table.integer('nbagrement');
    table.integer('nbterrasse');
    table.integer('nbpiscine');
    table.integer('ndroit');
    table.integer('ndroitindi');
    table.integer('ndroitpro');
    table.integer('ndroitges');
    table.string('catpro2');
    table.string('catpro2txt');
    table.string('catpro3');
    table.string('catpropro2');
    table.string('catproges2');
    table.string('locprop', 1);
    table.string('locproptxt');
    table.specificType('geomloc', 'geometry(Point, 4326)');
    table.string('source_geo');
    table.string('vecteur', 1);
    table.string('ban_id');
    table.string('ban_type');
    table.decimal('ban_score');
    table.string('ban_cp', 5);
    table.specificType('ban_geom', 'geometry(Point, 4326)');
    table.integer('dis_ban_ff');
    table.string('rnb_id');
    table.string('rnb_id_score', 1);
    table.specificType('geomrnb', 'geometry(Point, 4326)');
    table.integer('idpk');

    table.index('idprocpte');
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTable(TABLE);
}
