nodeLinker: pnpm

packageExtensions:
  "@codegouvfr/react-dsfr@*":
    dependencies:
      react: "*"
  "@turf/dissolve@*":
    dependencies:
      "@turf/flatten": "*"
  knex@*:
    dependencies:
      pg-query-stream: "*"
  postcss-loader@*:
    dependencies:
      browserslist: "*"
      postcss-flexbugs-fixes: "*"
      postcss-normalize: "*"
      postcss-preset-env: "*"
  sass-loader@*:
    dependencies:
      sass: "*"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
