nodeLinker: pnpm

packageExtensions:
  "@codegouvfr/react-dsfr@*":
    dependencies:
      "react": "*"
  "@turf/dissolve@*":
    dependencies:
      "@turf/flatten": "*"
  "postcss-loader@*":
    dependencies:
      "browserslist": "*"
      "postcss-flexbugs-fixes": "*"
      "postcss-preset-env": "*"
      "postcss-normalize": "*"
  "sass-loader@*":
    dependencies:
      "sass": "*"
