nodeLinker: node-modules

# Security: Disable execution of install scripts by default
# Prevents arbitrary code execution from malicious packages
# This is the equivalent of npm's "ignore-scripts=true"
#
# Allowlist for trusted packages is configured in package.json via:
# "dependenciesMeta": {
#   "<package-name>": { "built": true }
# }
enableScripts: false
