nodeLinker: pnpm

packageExtensions:
  "@codegouvfr/react-dsfr@*":
    dependencies:
      react: "*"
  "@turf/dissolve@*":
    dependencies:
      "@turf/flatten": "*"
  postcss-loader@*:
    dependencies:
      browserslist: "*"
      postcss-flexbugs-fixes: "*"
      postcss-normalize: "*"
      postcss-preset-env: "*"
  sass-loader@*:
    dependencies:
      sass: "*"
