nodeLinker: pnpm

packageExtensions:
  "@codegouvfr/react-dsfr@*":
    dependencies:
      "@types/react": "^18"
      "react": "^18"
  "@pdfme/pdf-lib@*":
    dependencies:
      tslib: "*"
  "@pdfme/schemas@*":
    dependencies:
      "bwip-js": "*"
  "@turf/dissolve@*":
    dependencies:
      "@turf/flatten": "*"
  knex@*:
    dependencies:
      pg-query-stream: "*"
  postcss-loader@*:
    dependencies:
      browserslist: "*"
      postcss-flexbugs-fixes: "*"
      postcss-normalize: "*"
      postcss-preset-env: "*"
  posthog-js@*:
    peerDependencies:
      react: "*"
  sass-loader@*:
    dependencies:
      sass: "*"
