{% macro process_owner_code_droit(ff_ccodro) %}
    CASE
        WHEN {{ ff_ccodro }} = 'P' THEN 'PROPRIETAIRE'
        WHEN {{ ff_ccodro }} = 'U' THEN 'USUFRUITIER'
        WHEN {{ ff_ccodro }} = 'N' THEN 'NU-PROPRIETAIRE'
        WHEN {{ ff_ccodro }} = 'R' THEN 'PRENEUR A CONSTRUCTION'
        WHEN {{ ff_ccodro }} = 'F' THEN 'FONCIER'
        WHEN {{ ff_ccodro }} = 'T' THEN 'TENUYER'
        WHEN {{ ff_ccodro }} = 'D' THEN 'DOMANIER'
        WHEN {{ ff_ccodro }} = 'V' THEN 'BAILLEUR D UN BAIL A REHABILITATION'
        WHEN {{ ff_ccodro }} = 'W' THEN 'PRENEUR D UN BAIL A REHABILITATION'
        WHEN {{ ff_ccodro }} = 'A' THEN 'LOCATAIRE-ATTRIBUTAIRE'
        WHEN {{ ff_ccodro }} = 'E' THEN 'EMPHYTEOTE'
        WHEN {{ ff_ccodro }} = 'K' THEN 'ANTICHRESISTE'
        WHEN {{ ff_ccodro }} = 'L' THEN 'FONCTIONNAIRE LOGE'
        WHEN {{ ff_ccodro }} = 'G' THEN 'GERANT, MANDATAIRE,GESTIONNAIRE'
        WHEN {{ ff_ccodro }} = 'S' THEN 'SYNDIC DE COPROPRIETE'
        WHEN {{ ff_ccodro }} = 'H' THEN 'ASSOCIE DANS UNE SOCIETE EN TRANSPARENCE FISCALE'
        WHEN {{ ff_ccodro }} = 'O' THEN 'AUTORISATION DOCCUPATION TEMPORAIRE'
        WHEN {{ ff_ccodro }} = 'J' THEN 'JEUNE AGRICULTEUR'
        WHEN {{ ff_ccodro }} = 'Q' THEN 'GESTIONNAIRE TAXE SUR LES BUREAUX'
        WHEN {{ ff_ccodro }} = 'X' THEN 'LA POSTE PROPRIETAIRE ET OCCUPANT'
        WHEN {{ ff_ccodro }} = 'Y' THEN 'LA POSTE OCCUPANT - NON PROPRIETAIRE'
        WHEN {{ ff_ccodro }} = 'C' THEN 'FIDUCIAIRE'
        WHEN {{ ff_ccodro }} = 'M' THEN 'OCCUPANT D UNE PARCELLE APPARTENANT AU DEPARTEMENT DE MAYOTTE OU A L ETAT'
        WHEN {{ ff_ccodro }} = 'Z' THEN 'GESTIONNAIRE D UN BIEN DE L ETAT'
        WHEN {{ ff_ccodro }} = 'B' THEN 'BAILLEUR A CONSTRUCTION'
        ELSE 'NON SPECIFIE'
    END
{% endmacro %}
