SELECT
    ANNEE_MODIF AS YEAR,
    CAST(COM_INI AS VARCHAR) AS GEO_CODE_SOURCE,
    CAST(COM_FIN AS VARCHAR) AS GEO_CODE_DESTINATION,
    LIB_COM_INI AS LIBELLE_SOURCE,
    LIB_COM_FIN AS LIBELLE_DESTINATION
FROM {{ ref ('fusions') }}
