version: 2


models:
  - name: stg_lovac_ff_ext_2024
  - name: stg_lovac_ff_ext_2023
  - name: stg_lovac_ff_ext_2022
  - name: stg_lovac_ff_ext_2021
  - name: stg_lovac_ff_ext_2020
  - name: stg_lovac_ff_ext_2019
    