version: 2

sources:
  - name: duckdb_raw
    schema: external
    tables:
      - name: cerema_lovac_ff_ext_2024_raw
      - name: cerema_lovac_ff_ext_2023_raw
      - name: cerema_lovac_ff_ext_2022_raw
      - name: cerema_lovac_ff_ext_2021_raw
      - name: cerema_lovac_ff_ext_2020_raw
      - name: cerema_lovac_ff_ext_2019_raw
