version: 2

models:
  - name: marts_analysis_housing_out_features
    description: Table d'analyse au niveau logement avec indicateur de sortie de vacance
    columns:
      - name: housing_id
        description: Identifiant unique du logement
        tests:
          - not_null
          - unique
      - name: is_housing_out
        description: Variable cible 1=sorti, 0=toujours vacant
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]

  - name: marts_analysis_city_aggregated
    description: Table d'analyse agregee au niveau commune avec taux de sortie de vacance
    columns:
      - name: geo_code
        description: Code commune
        tests:
          - not_null
          - unique

  - name: marts_bi_housing_characteristics
    description: |
      Table BI - Caracteristiques intrinseques des logements pour l'analyse de sortie de vacance.
      Granularite Logement. Variable cible is_housing_out.
      Features - Type de logement, taille, age du batiment, DPE, confort, duree de vacance, fiscalite, mutations.
    columns:
      - name: housing_id
        description: Identifiant unique du logement
        tests:
          - not_null
          - unique
      - name: is_housing_out
        description: Variable cible 1=sorti, 0=toujours vacant
      - name: housing_kind
        description: Type de logement maison ou appartement
      - name: living_area_category
        description: Categorie de surface
      - name: energy_consumption_category
        description: Categorie DPE Performant Moyen Passoire
      - name: is_energy_sieve
        description: TRUE si passoire energetique F ou G
      - name: vacancy_duration_category
        description: Categorie de duree 0-2 ans, 3-5 ans, 6-10 ans, Plus de 10 ans
      - name: vacancy_severity
        description: Severite de la vacance combinaison duree energie cadastre

  - name: marts_bi_housing_geography
    description: |
      Table BI - Contexte geographique et territorial des logements.
      Features - Localisation, densite, demographie, zonage ABC, prix immobilier, loyers, dynamisme marche, fiscalite, territoires speciaux.
    columns:
      - name: housing_id
        description: Identifiant unique du logement
        tests:
          - not_null
          - unique
      - name: densite_category
        description: Categorie de densite Urbain dense, Urbain intermediaire, Rural
      - name: zonage_category
        description: Zone tendue ou detendue
      - name: niveau_loyer
        description: Categorie de loyer Tres eleve, Eleve, Moyen, Modere, Faible
      - name: dvg_marche_dynamisme
        description: Dynamisme du marche
      - name: is_in_tlv_territory
        description: TRUE si en zone TLV
      - name: has_any_special_territory
        description: TRUE si au moins un programme special

  - name: marts_bi_housing_owners
    description: |
      Table BI - Profil des proprietaires rang=1 uniquement.
      Features - Type de proprietaire, demographie, localisation relative, distance, droits de propriete, multi-propriete, contactabilite.
    columns:
      - name: housing_id
        description: Identifiant unique du logement
        tests:
          - not_null
          - unique
      - name: owner_kind_category
        description: Categorie de proprietaire Particulier, SCI, Autre PM, Indivision
      - name: owner_is_individual
        description: TRUE si particulier
      - name: owner_age_category
        description: Categorie d age
      - name: owner_is_local
        description: TRUE si proprietaire local
      - name: owner_is_distant
        description: TRUE si proprietaire distant
      - name: owner_is_multi_owner
        description: TRUE si multi-proprietaire
      - name: owner_contactable
        description: TRUE si email ou telephone disponible

  - name: marts_zlv_usage
    description: |
      Table etablissement - Metriques d utilisation de ZLV par etablissement.
      Grain: un enregistrement par etablissement (CC, CU, ME, CA, Commune, SIVOM, CTU).
      Source principale: int_analysis_establishments_zlv_usage enrichi avec les Echelons inscrits.
      Sections: Dimensions, Utilisateurs/Connexions, Logements MAJ Situation, Logements MAJ Enrichissement,
      Documents, Groupes, Campagnes, Perimetres, Referents comparatifs, Prise de contact, Echelons inscrits.
    columns:
      - name: establishment_id
        description: Identifiant unique de l etablissement
        tests:
          - not_null
          - unique
      - name: nom
        description: Nom de l etablissement
      - name: ouvert
        description: TRUE si l etablissement est ouvert et a au moins un utilisateur
      - name: kind
        description: Type d etablissement (CC, CU, ME, CA, Commune, SIVOM, CTU)
      - name: type_simple
        description: Type regroupe (Intercommunalite, Commune, Autre)
      - name: type_detaille
        description: Type detaille (Metropole, Communaute d Agglomeration, etc.)
      - name: communes_inscrites
        description: Nombre de communes inscrites dans ZLV au sein du territoire de l intercommunalite (NULL pour communes)
      - name: communes_inscrites_pct
        description: Pourcentage de communes inscrites dans ZLV sur total communes du territoire (NULL pour communes)
      - name: intercommunalites_inscrites
        description: Nombre d intercommunalites inscrites (NULL pour collectivites locales - echelon departemental)
      - name: departements_inscrits
        description: Nombre de departements inscrits (NULL pour collectivites locales - echelon regional)
      - name: sded_inscrits
        description: Nombre de SDED inscrits (NULL pour collectivites locales - echelon regional)

  - name: marts_bi_housing_zlv_usage
    description: |
      Table BI - Utilisation de l application ZLV et activite des etablissements au niveau logement.
      Mapping: Housing geo_code -> EPCI/CA/CC/ME via int_production_establishments_localities.
      Contient les metriques au niveau logement (contact, statuts, campagnes) ET les metriques
      agregees au niveau etablissement (prefixe establishment_) jointes depuis marts_zlv_usage via mapping EPCI.
      Question cle - L utilisation de ZLV est-elle un determinant de la sortie de vacance?
    columns:
      - name: housing_id
        description: Identifiant unique du logement
        tests:
          - not_null
          - unique
      - name: was_contacted_by_zlv
        description: TRUE si le logement a ete contacte par ZLV
      - name: contact_intensity
        description: Intensite de contact Non contacte, 1 contact, 2-3 contacts, 4+ contacts
      - name: typologie_activation_simple
        description: Typologie d activation de la CT
      - name: activation_level
        description: Niveau d activation 1-5
      - name: kind_pro_activity_ntile
        description: Categorie de pro-activite
      - name: zlv_engagement_score
        description: Score d engagement ZLV 0-10
      - name: zlv_engagement_category
        description: Categorie d engagement Aucun, Faible, Moyen, Fort
      - name: establishment_nom
        description: Nom de l etablissement
      - name: establishment_ouvert
        description: TRUE si l etablissement est ouvert et actif
      - name: establishment_date_ouverture
        description: Date de premiere activation
      - name: establishment_annee_ouverture
        description: Annee de premiere activation
      - name: establishment_utilisateurs_inscrits
        description: Nombre d utilisateurs inscrits
      - name: establishment_connexions_30_jours
        description: Nombre d utilisateurs actifs dans les 30 derniers jours (proxy)
      - name: establishment_connexions_60_jours
        description: Nombre d utilisateurs actifs dans les 60 derniers jours (proxy)
      - name: establishment_connexions_90_jours
        description: Nombre d utilisateurs actifs dans les 90 derniers jours (proxy)
      - name: establishment_logements_maj_situation
        description: Nombre de logements avec MAJ situation dans l etablissement
      - name: establishment_logements_maj_occupation
        description: Nombre de logements avec MAJ occupation dans l etablissement
      - name: establishment_logements_maj_suivi
        description: Nombre de logements avec MAJ suivi dans l etablissement
      - name: establishment_logements_maj_enrichissement
        description: Nombre de logements avec MAJ enrichissement dans l etablissement
      - name: establishment_logements_maj_mails
        description: Nombre de logements avec MAJ email proprietaire
      - name: establishment_logements_maj_phone
        description: Nombre de logements avec MAJ telephone proprietaire
      - name: establishment_logements_maj_owners
        description: Nombre de logements avec MAJ nom ou rang proprietaire
      - name: establishment_logements_maj_owners_address
        description: Nombre de logements avec MAJ adresse proprietaire
      - name: establishment_logements_maj_notes
        description: Nombre de logements avec notes utilisateur
      - name: establishment_logements_maj_documents
        description: Nombre de logements avec au moins 1 document
      - name: establishment_documents_importes
        description: Nombre total de documents importes
      - name: establishment_logements_contactes_via_campagnes
        description: Nombre de logements contactes via campagnes
      - name: establishment_logements_exportes_via_groupes
        description: Nombre de logements exportes via groupes
      - name: establishment_campagnes_creees
        description: Nombre total de campagnes creees
      - name: establishment_campagnes_envoyees
        description: Nombre total de campagnes envoyees
      - name: establishment_groupes_crees
        description: Nombre total de groupes crees
      - name: establishment_perimetres_importes
        description: Nombre total de perimetres importes
      - name: establishment_region
        description: Region de l etablissement
      - name: establishment_departement
        description: Departement de l etablissement
      - name: establishment_type_detaille
        description: Type detaille de l etablissement
      - name: establishment_type_simple
        description: Type simple de l etablissement
      - name: establishment_mails_utilisateurs
        description: Emails des utilisateurs de l etablissement

  - name: marts_bi_housing_complete
    description: |
      Table BI complete - Jointure de toutes les dimensions pour l analyse des determinants.
      Table principale pour analyser les facteurs de sortie de vacance et mesurer l impact de ZLV.
      Dimensions - Caracteristiques logement, contexte geographique, profil proprietaire, usage ZLV.
      Features d interaction - owner_x_territory, housing_x_market, vacancy_x_energy, contact_x_activation.
      Flags d analyse - is_favorable_for_exit, is_at_risk_long_vacancy, zlv_treatment_group.
    columns:
      - name: housing_id
        description: Identifiant unique du logement
        tests:
          - not_null
          - unique
      - name: is_housing_out
        description: Variable cible 1=sorti, 0=toujours vacant
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: owner_x_territory
        description: Interaction proprietaire x territoire
      - name: housing_x_market
        description: Interaction logement x marche
      - name: vacancy_x_energy
        description: Interaction vacance x energie
      - name: contact_x_activation
        description: Interaction contact ZLV x activation CT
      - name: is_favorable_for_exit
        description: TRUE si conditions favorables a la sortie
      - name: is_at_risk_long_vacancy
        description: TRUE si risque de vacance longue
      - name: zlv_treatment_group
        description: Groupe de traitement pour analyse quasi-experimentale
      - name: total_count
        description: Toujours 1, utile pour les agregations BI
