---
- name: Configurer la base de données PostgreSQL
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/db_configuration.yml
    - vars/db_credentials.yml
  vars_prompt:
    - name: create_indices_for_housing
      prompt: "Créer les indices pour la table des propriétaires ? (yes/no)"
      private: no

    - name: create_indices_for_owners
      prompt: "Créer les indices pour la table des logements ? (yes/no)"
      private: no
  tasks:
    - name: Créer la base de données
      postgresql_db:
        name: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        port: "{{ db_port }}"
        state: present

    - name: Créer le schéma
      postgresql_schema:
        name: "{{ schema_name }}"
        database: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        port: "{{ db_port }}"
        state: present

    - name: Créer le rôle
      postgresql_user:
        name: "{{ role_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        state: present

    - name: Ajouter l'extension PostGIS
      postgresql_ext:
        name: postgis
        db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        port: "{{ db_port }}"

    - name: Vérifier si la table originale existe
      ansible.builtin.command: >
        psql -qtAX -h {{ db_host }} -p {{ db_port }} -d {{ db_name }} -U {{ db_user }} -c "SELECT to_regclass('{{ schema_name }}.{{ table_name }}')"
      register: table_origin_check
      changed_when: false
      ignore_errors: true

    - name: Vérifier si la table finale existe
      ansible.builtin.command: >
        psql -qtAX -h {{ db_host }} -p {{ db_port }} -d {{ db_name }} -U {{ db_user }} -c "SELECT to_regclass('{{ final_table_name }}')"
      register: table_finale_check
      changed_when: false
      ignore_errors: true

    - name: Exécuter le script SQL d'import des données
      ansible.builtin.command: >
        psql -h {{ db_host }} -p {{ db_port }} -d {{ db_name }} -U {{ db_user }} -f {{ script_file_path }}/{{ table_name }}/{{ table_name }}.sql
      when: table_origin_check.stdout == "" and table_finale_check.stdout != final_table_name

    - name: Vérifier si la table finale existe
      ansible.builtin.command: >
        psql -qtAX -h {{ db_host }} -p {{ db_port }} -d {{ db_name }} -U {{ db_user }} -c "SELECT to_regclass('{{ final_table_name }}')"
      register: table_finale_check
      changed_when: false
      ignore_errors: true

    - name: Renommer la table et la déplacer dans le schéma public
      ansible.builtin.command: >
        psql -qtAX -h {{ db_host }} -p {{ db_port }} -d {{ db_name }} -U {{ db_user }} -c "ALTER TABLE {{ schema_name }}.{{ table_name }} RENAME TO {{ final_table_name }};ALTER TABLE {{ schema_name }}.{{ final_table_name }} SET SCHEMA public;"
      when: table_finale_check.stdout != final_table_name

    - name: Créer les indices pour la table des logements
      ansible.builtin.command: >
        psql -qtAX -h {{ db_host }} -p {{ db_port }} -d {{ db_name }} -U {{ db_user }} -c "{{ item }}"
      loop:
        - "CREATE INDEX IF NOT EXISTS idx_idlocal_ccthp ON {{ schema_name }}.{{ final_table_name }} (idlocal, ccthp)"
        - "CREATE INDEX IF NOT EXISTS idx_dteloctxt ON {{ schema_name }}.{{ final_table_name }} (dteloctxt)"
        - "CREATE INDEX IF NOT EXISTS idx_ccthp_dteloctxt ON {{ schema_name }}.{{ final_table_name }} (ccthp, dteloctxt)"
      when: create_indices_for_housing == "yes"
      register: indices_creation_housing
      changed_when: false
      ignore_errors: true

    - name: Créer les indices pour la table des propriétaires
      ansible.builtin.command: >
        psql -qtAX -h {{ db_host }} -p {{ db_port }} -d {{ db_name }} -U {{ db_user }} -c "{{ item }}"
      loop:
        - "CREATE INDEX IF NOT EXISTS idx_idprocpte ON {{ schema_name }}.{{ final_table_name }} (idprocpte)"
        - "CREATE INDEX IF NOT EXISTS idx_dnulp ON {{ schema_name }}.{{ final_table_name }} (dnulp)"
        - "CREATE INDEX IF NOT EXISTS idx_ccogrm ON {{ schema_name }}.{{ final_table_name }} (ccogrm)"
        - "CREATE INDEX IF NOT EXISTS idx_not_null_ddenom ON {{ schema_name }}.{{ final_table_name }} (ddenom) WHERE ddenom IS NOT NULL"
        - "CREATE INDEX IF NOT EXISTS idx_non_null_dlign3 ON {{ schema_name }}.{{ final_table_name }} (dlign3) WHERE dlign3 IS NULL"
        - "CREATE INDEX IF NOT EXISTS idx_non_null_dlign4 ON {{ schema_name }}.{{ final_table_name }} (dlign4) WHERE dlign4 IS NULL"
        - "CREATE INDEX IF NOT EXISTS idx_non_null_dlign5 ON {{ schema_name }}.{{ final_table_name }} (dlign5) WHERE dlign5 IS NULL"
        - "CREATE INDEX IF NOT EXISTS idx_non_null_dlign6 ON {{ schema_name }}.{{ final_table_name }} (dlign6) WHERE dlign6 IS NULL"
        - "CREATE INDEX IF NOT EXISTS idx_idpersonne ON {{ schema_name }}.{{ final_table_name }}(idpersonne)"
      when: create_indices_for_owners == "yes"
      register: indices_creation_owners
      changed_when: false
      ignore_errors: true

