version: 2

sources:
  - name: duckdb_production_raw
    schema: production
    tables:
      - name: housing
      - name: owners
      - name: events
      - name: old_events
      - name: housing_events
      - name: establishments
      - name: users
      - name: campaigns_housing
      - name: campaigns
      - name: owners_housing
      - name: group_housing_events
      - name: groups
      - name: groups_housing
      - name: geo_perimeters
