-- Auto-generated schema for dpe_raw table
-- Generated from DPE JSONL data

DROP TABLE IF EXISTS dpe_raw CASCADE;

CREATE TABLE dpe_raw (
    -- Primary key
    dpe_id TEXT PRIMARY KEY,

    -- Location and identification
    adresse_ban TEXT,
    adresse_brut TEXT,
    code_departement_ban TEXT,
    code_insee_ban TEXT,
    code_postal_ban TEXT,
    code_postal_brut BIGINT,
    code_region_ban TEXT,
    complement_adresse_batiment TEXT,
    complement_adresse_logement TEXT,
    identifiant_ban TEXT,
    nom_commune_ban TEXT,
    nom_commune_brut TEXT,
    nom_residence TEXT,
    nom_rue_ban TEXT,
    numero_dpe TEXT,
    numero_dpe_immeuble_associe TEXT,
    numero_dpe_remplace TEXT,
    numero_etage_appartement BIGINT,
    numero_immatriculation_copropriete TEXT,
    numero_voie_ban TEXT,

    -- RNB (Référentiel National des Bâtiments) fields
    id_rnb TEXT,
    provenance_id_rnb TEXT,

    -- Performance metrics
    conso_5_usages_ef NUMERIC,
    conso_5_usages_ef_energie_n1 NUMERIC,
    conso_5_usages_ef_energie_n2 NUMERIC,
    conso_5_usages_ef_energie_n3 NUMERIC,
    conso_5_usages_ep NUMERIC,
    conso_5_usages_par_m2_ef NUMERIC,
    conso_5_usages_par_m2_ep NUMERIC,
    conso_auxiliaires_ef NUMERIC,
    conso_auxiliaires_ep NUMERIC,
    conso_chauffage_ef NUMERIC,
    conso_chauffage_ef_energie_n1 NUMERIC,
    conso_chauffage_ef_energie_n2 NUMERIC,
    conso_chauffage_ef_energie_n3 NUMERIC,
    conso_chauffage_ep NUMERIC,
    conso_chauffage_generateur_n1_installation_n1 NUMERIC,
    conso_chauffage_generateur_n1_installation_n2 NUMERIC,
    conso_chauffage_generateur_n2_installation_n1 NUMERIC,
    conso_chauffage_generateur_n2_installation_n2 NUMERIC,
    conso_chauffage_installation_chauffage_n1 NUMERIC,
    conso_chauffage_installation_chauffage_n2 NUMERIC,
    conso_eclairage_ef NUMERIC,
    conso_eclairage_ep NUMERIC,
    conso_ecs_ef NUMERIC,
    conso_ecs_ef_energie_n1 NUMERIC,
    conso_ecs_ef_energie_n2 NUMERIC,
    conso_ecs_ef_energie_n3 NUMERIC,
    conso_ecs_ep NUMERIC,
    conso_ef_generateur_n1_ecs_n1 NUMERIC,
    conso_ef_generateur_n2_ecs_n1 NUMERIC,
    conso_ef_installation_ecs_n1 NUMERIC,
    conso_refroidissement_annuel NUMERIC,
    conso_refroidissement_ef NUMERIC,
    conso_refroidissement_ep NUMERIC,
    cout_auxiliaires NUMERIC,
    cout_chauffage NUMERIC,
    cout_chauffage_energie_n1 NUMERIC,
    cout_chauffage_energie_n2 NUMERIC,
    cout_chauffage_energie_n3 NUMERIC,
    cout_eclairage NUMERIC,
    cout_ecs NUMERIC,
    cout_ecs_energie_n1 NUMERIC,
    cout_ecs_energie_n2 NUMERIC,
    cout_ecs_energie_n3 NUMERIC,
    cout_refroidissement NUMERIC,
    cout_total_5_usages NUMERIC,
    cout_total_5_usages_energie_n1 NUMERIC,
    cout_total_5_usages_energie_n2 NUMERIC,
    cout_total_5_usages_energie_n3 NUMERIC,
    emission_ges_5_usages NUMERIC,
    emission_ges_5_usages_energie_n1 NUMERIC,
    emission_ges_5_usages_energie_n2 NUMERIC,
    emission_ges_5_usages_energie_n3 NUMERIC,
    emission_ges_5_usages_par_m2 NUMERIC,
    emission_ges_auxiliaires NUMERIC,
    emission_ges_chauffage NUMERIC,
    emission_ges_chauffage_energie_n1 NUMERIC,
    emission_ges_chauffage_energie_n2 NUMERIC,
    emission_ges_chauffage_energie_n3 NUMERIC,
    emission_ges_eclairage NUMERIC,
    emission_ges_ecs NUMERIC,
    emission_ges_ecs_energie_n1 NUMERIC,
    emission_ges_ecs_energie_n2 NUMERIC,
    emission_ges_ecs_energie_n3 NUMERIC,
    emission_ges_refroidissement NUMERIC,
    etiquette_dpe TEXT,
    etiquette_ges TEXT,

    -- Technical details
    configuration_installation_chauffage_n1 TEXT,
    configuration_installation_chauffage_n2 TEXT,
    configuration_installation_ecs_n1 TEXT,
    description_generateur_chauffage_n1_installation_n1 TEXT,
    description_generateur_chauffage_n1_installation_n2 TEXT,
    description_generateur_chauffage_n2_installation_n1 TEXT,
    description_generateur_chauffage_n2_installation_n2 TEXT,
    description_generateur_froid TEXT,
    description_generateur_n1_ecs_n1 TEXT,
    description_generateur_n2_ecs_n1 TEXT,
    description_installation_chauffage_n1 TEXT,
    description_installation_chauffage_n2 TEXT,
    description_installation_ecs_n1 TEXT,
    facteur_couverture_solaire_installation_chauffage_n1 NUMERIC,
    facteur_couverture_solaire_saisi_installation_chauffage_n1 NUMERIC,
    nombre_logements_desservis_par_installation_ecs_n1 BIGINT,
    periode_installation_generateur_froid TEXT,
    production_ecs_solaire_installation_n1 NUMERIC,
    qualite_isolation_enveloppe TEXT,
    qualite_isolation_menuiseries TEXT,
    qualite_isolation_murs TEXT,
    qualite_isolation_plancher_bas TEXT,
    qualite_isolation_plancher_haut_comble_amenage TEXT,
    qualite_isolation_plancher_haut_comble_perdu TEXT,
    qualite_isolation_plancher_haut_toit_terrasse TEXT,
    surface_chauffee_installation_chauffage_n1 NUMERIC,
    surface_chauffee_installation_chauffage_n2 NUMERIC,
    surface_habitable_desservie_par_installation_ecs_n1 NUMERIC,
    type_batiment TEXT,
    type_emetteur_installation_chauffage_n1 TEXT,
    type_emetteur_installation_chauffage_n2 TEXT,
    type_energie_climatisation TEXT,
    type_energie_generateur_n1_ecs_n1 TEXT,
    type_energie_generateur_n1_installation_n1 TEXT,
    type_energie_generateur_n1_installation_n2 TEXT,
    type_energie_generateur_n2_ecs_n1 TEXT,
    type_energie_generateur_n2_installation_n1 TEXT,
    type_energie_generateur_n2_installation_n2 TEXT,
    type_energie_n1 TEXT,
    type_energie_n2 TEXT,
    type_energie_n3 TEXT,
    type_energie_principale_chauffage TEXT,
    type_energie_principale_ecs TEXT,
    type_generateur_chauffage_principal TEXT,
    type_generateur_chauffage_principal_ecs TEXT,
    type_generateur_froid TEXT,
    type_generateur_n1_ecs_n1 TEXT,
    type_generateur_n1_installation_n1 TEXT,
    type_generateur_n1_installation_n2 TEXT,
    type_generateur_n2_ecs_n1 TEXT,
    type_generateur_n2_installation_n1 TEXT,
    type_generateur_n2_installation_n2 TEXT,
    type_installation_chauffage TEXT,
    type_installation_chauffage_n1 TEXT,
    type_installation_chauffage_n2 TEXT,
    type_installation_ecs TEXT,
    type_installation_ecs_n1 TEXT,
    type_installation_solaire_n1 TEXT,
    type_ventilation TEXT,
    usage_generateur_n1_installation_n1 TEXT,
    usage_generateur_n1_installation_n2 TEXT,
    usage_generateur_n2_installation_n1 TEXT,
    usage_generateur_n2_installation_n2 TEXT,

    -- Dates
    date_derniere_modification_dpe DATE,
    date_etablissement_dpe DATE,
    date_fin_validite_dpe DATE,
    date_installation_generateur_n1_ecs_n1 DATE,
    date_installation_generateur_n2_ecs_n1 DATE,
    date_reception_dpe DATE,
    date_visite_diagnostiqueur DATE,

    -- Other fields
    _geopoint TEXT,
    _i BIGINT,
    _rand BIGINT,
    _score TEXT,
    annee_construction BIGINT,
    appartement_non_visite BIGINT,
    apport_interne_saison_chauffe NUMERIC,
    apport_interne_saison_froide NUMERIC,
    apport_solaire_saison_chauffe NUMERIC,
    apport_solaire_saison_froide NUMERIC,
    besoin_chauffage NUMERIC,
    besoin_ecs NUMERIC,
    besoin_refroidissement NUMERIC,
    categorie_enr TEXT,
    classe_altitude TEXT,
    classe_inertie_batiment TEXT,
    coordonnee_cartographique_x_ban NUMERIC,
    coordonnee_cartographique_y_ban NUMERIC,
    latitude NUMERIC,
    longitude NUMERIC,
    cop_generateur_n1_ecs_n1 NUMERIC,
    deperditions_baies_vitrees NUMERIC,
    deperditions_enveloppe NUMERIC,
    deperditions_murs NUMERIC,
    deperditions_planchers_bas NUMERIC,
    deperditions_planchers_hauts NUMERIC,
    deperditions_ponts_thermiques NUMERIC,
    deperditions_portes NUMERIC,
    deperditions_renouvellement_air NUMERIC,
    electricite_pv_autoconsommee NUMERIC,
    facteur_couverture_solaire_n1 NUMERIC,
    facteur_couverture_solaire_saisi_n1 NUMERIC,
    hauteur_sous_plafond NUMERIC,
    indicateur_confort_ete TEXT,
    inertie_lourde BIGINT,
    isolation_toiture BIGINT,
    logement_traversant BIGINT,
    methode_application_dpe TEXT,
    modele_dpe TEXT,
    nombre_appartement BIGINT,
    nombre_module BIGINT,
    nombre_niveau_immeuble BIGINT,
    nombre_niveau_logement BIGINT,
    periode_construction TEXT,
    position_logement_dans_immeuble TEXT,
    presence_brasseur_air BIGINT,
    presence_production_pv BIGINT,
    production_electricite_pv_kwhep_par_an NUMERIC,
    protection_solaire_exterieure BIGINT,
    score_ban NUMERIC,
    statut_geocodage TEXT,
    surface_climatisee NUMERIC,
    surface_habitable_immeuble NUMERIC,
    surface_habitable_logement NUMERIC,
    surface_tertiaire_immeuble NUMERIC,
    surface_totale_capteurs_pv NUMERIC,
    surface_ventilee NUMERIC,
    systeme_production_electricite_origine_renouvelable TEXT,
    typologie_logement TEXT,
    ubat_w_par_m2_k NUMERIC,
    usage_generateur_n1_ecs_n1 TEXT,
    usage_generateur_n2_ecs_n1 TEXT,
    ventilation_posterieure_2012 BIGINT,
    version_dpe NUMERIC,
    volume_stockage_generateur_n1_ecs_n1 NUMERIC,
    volume_stockage_generateur_n2_ecs_n1 BIGINT,
    zone_climatique TEXT
);

-- Indexes for common queries
CREATE INDEX idx_dpe_raw_code_insee ON dpe_raw(code_insee_ban);
CREATE INDEX idx_dpe_raw_code_postal ON dpe_raw(code_postal_ban);
CREATE INDEX idx_dpe_raw_code_departement ON dpe_raw(code_departement_ban);
CREATE INDEX idx_dpe_raw_etiquette_dpe ON dpe_raw(etiquette_dpe);
CREATE INDEX idx_dpe_raw_date_etablissement ON dpe_raw(date_etablissement_dpe);
CREATE INDEX idx_dpe_raw_type_batiment ON dpe_raw(type_batiment);
CREATE INDEX idx_dpe_raw_numero_dpe ON dpe_raw(numero_dpe);
CREATE INDEX idx_dpe_raw_id_rnb ON dpe_raw(id_rnb) WHERE id_rnb IS NOT NULL;
CREATE INDEX idx_dpe_raw_provenance_id_rnb ON dpe_raw(provenance_id_rnb);

-- Spatial index for location-based queries (using BAN cartographic coordinates)
CREATE INDEX idx_dpe_raw_location ON dpe_raw(coordonnee_cartographique_x_ban, coordonnee_cartographique_y_ban) WHERE coordonnee_cartographique_x_ban IS NOT NULL AND coordonnee_cartographique_y_ban IS NOT NULL;

-- Spatial index for latitude/longitude
CREATE INDEX idx_dpe_raw_lat_lon ON dpe_raw(latitude, longitude) WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

COMMENT ON TABLE dpe_raw IS 'Raw DPE (Diagnostic de Performance Énergétique) data from ADEME';