"""Auto-generated field list for DPE raw data import"""

# All fields in the dpe_raw table
DPE_RAW_FIELDS = [
    "_geopoint",
    "_i",
    "dpe_id",
    "_rand",
    "_score",
    "adresse_ban",
    "adresse_brut",
    "annee_construction",
    "appartement_non_visite",
    "apport_interne_saison_chauffe",
    "apport_interne_saison_froide",
    "apport_solaire_saison_chauffe",
    "apport_solaire_saison_froide",
    "besoin_chauffage",
    "besoin_ecs",
    "besoin_refroidissement",
    "categorie_enr",
    "classe_altitude",
    "classe_inertie_batiment",
    "code_departement_ban",
    "code_insee_ban",
    "code_postal_ban",
    "code_postal_brut",
    "code_region_ban",
    "complement_adresse_batiment",
    "complement_adresse_logement",
    "configuration_installation_chauffage_n1",
    "configuration_installation_chauffage_n2",
    "configuration_installation_ecs_n1",
    "conso_5_usages_ef",
    "conso_5_usages_ef_energie_n1",
    "conso_5_usages_ef_energie_n2",
    "conso_5_usages_ef_energie_n3",
    "conso_5_usages_ep",
    "conso_5_usages_par_m2_ef",
    "conso_5_usages_par_m2_ep",
    "conso_auxiliaires_ef",
    "conso_auxiliaires_ep",
    "conso_chauffage_ef",
    "conso_chauffage_ef_energie_n1",
    "conso_chauffage_ef_energie_n2",
    "conso_chauffage_ef_energie_n3",
    "conso_chauffage_ep",
    "conso_chauffage_generateur_n1_installation_n1",
    "conso_chauffage_generateur_n1_installation_n2",
    "conso_chauffage_generateur_n2_installation_n1",
    "conso_chauffage_generateur_n2_installation_n2",
    "conso_chauffage_installation_chauffage_n1",
    "conso_chauffage_installation_chauffage_n2",
    "conso_eclairage_ef",
    "conso_eclairage_ep",
    "conso_ecs_ef",
    "conso_ecs_ef_energie_n1",
    "conso_ecs_ef_energie_n2",
    "conso_ecs_ef_energie_n3",
    "conso_ecs_ep",
    "conso_ef_generateur_n1_ecs_n1",
    "conso_ef_generateur_n2_ecs_n1",
    "conso_ef_installation_ecs_n1",
    "conso_refroidissement_annuel",
    "conso_refroidissement_ef",
    "conso_refroidissement_ep",
    "coordonnee_cartographique_x_ban",
    "coordonnee_cartographique_y_ban",
    "cop_generateur_n1_ecs_n1",
    "cout_auxiliaires",
    "cout_chauffage",
    "cout_chauffage_energie_n1",
    "cout_chauffage_energie_n2",
    "cout_chauffage_energie_n3",
    "cout_eclairage",
    "cout_ecs",
    "cout_ecs_energie_n1",
    "cout_ecs_energie_n2",
    "cout_ecs_energie_n3",
    "cout_refroidissement",
    "cout_total_5_usages",
    "cout_total_5_usages_energie_n1",
    "cout_total_5_usages_energie_n2",
    "cout_total_5_usages_energie_n3",
    "date_derniere_modification_dpe",
    "date_etablissement_dpe",
    "date_fin_validite_dpe",
    "date_installation_generateur_n1_ecs_n1",
    "date_installation_generateur_n2_ecs_n1",
    "date_reception_dpe",
    "date_visite_diagnostiqueur",
    "deperditions_baies_vitrees",
    "deperditions_enveloppe",
    "deperditions_murs",
    "deperditions_planchers_bas",
    "deperditions_planchers_hauts",
    "deperditions_ponts_thermiques",
    "deperditions_portes",
    "deperditions_renouvellement_air",
    "description_generateur_chauffage_n1_installation_n1",
    "description_generateur_chauffage_n1_installation_n2",
    "description_generateur_chauffage_n2_installation_n1",
    "description_generateur_chauffage_n2_installation_n2",
    "description_generateur_froid",
    "description_generateur_n1_ecs_n1",
    "description_generateur_n2_ecs_n1",
    "description_installation_chauffage_n1",
    "description_installation_chauffage_n2",
    "description_installation_ecs_n1",
    "electricite_pv_autoconsommee",
    "emission_ges_5_usages",
    "emission_ges_5_usages_energie_n1",
    "emission_ges_5_usages_energie_n2",
    "emission_ges_5_usages_energie_n3",
    "emission_ges_5_usages_par_m2",
    "emission_ges_auxiliaires",
    "emission_ges_chauffage",
    "emission_ges_chauffage_energie_n1",
    "emission_ges_chauffage_energie_n2",
    "emission_ges_chauffage_energie_n3",
    "emission_ges_eclairage",
    "emission_ges_ecs",
    "emission_ges_ecs_energie_n1",
    "emission_ges_ecs_energie_n2",
    "emission_ges_ecs_energie_n3",
    "emission_ges_refroidissement",
    "etiquette_dpe",
    "etiquette_ges",
    "facteur_couverture_solaire_installation_chauffage_n1",
    "facteur_couverture_solaire_n1",
    "facteur_couverture_solaire_saisi_installation_chauffage_n1",
    "facteur_couverture_solaire_saisi_n1",
    "hauteur_sous_plafond",
    "identifiant_ban",
    "indicateur_confort_ete",
    "inertie_lourde",
    "isolation_toiture",
    "logement_traversant",
    "methode_application_dpe",
    "modele_dpe",
    "nom_commune_ban",
    "nom_commune_brut",
    "nom_residence",
    "nom_rue_ban",
    "nombre_appartement",
    "nombre_logements_desservis_par_installation_ecs_n1",
    "nombre_module",
    "nombre_niveau_immeuble",
    "nombre_niveau_logement",
    "numero_dpe",
    "numero_dpe_immeuble_associe",
    "numero_dpe_remplace",
    "numero_etage_appartement",
    "numero_immatriculation_copropriete",
    "numero_voie_ban",
    "periode_construction",
    "periode_installation_generateur_froid",
    "position_logement_dans_immeuble",
    "presence_brasseur_air",
    "presence_production_pv",
    "production_ecs_solaire_installation_n1",
    "production_electricite_pv_kwhep_par_an",
    "protection_solaire_exterieure",
    "qualite_isolation_enveloppe",
    "qualite_isolation_menuiseries",
    "qualite_isolation_murs",
    "qualite_isolation_plancher_bas",
    "qualite_isolation_plancher_haut_comble_amenage",
    "qualite_isolation_plancher_haut_comble_perdu",
    "qualite_isolation_plancher_haut_toit_terrasse",
    "score_ban",
    "statut_geocodage",
    "surface_chauffee_installation_chauffage_n1",
    "surface_chauffee_installation_chauffage_n2",
    "surface_climatisee",
    "surface_habitable_desservie_par_installation_ecs_n1",
    "surface_habitable_immeuble",
    "surface_habitable_logement",
    "surface_tertiaire_immeuble",
    "surface_totale_capteurs_pv",
    "surface_ventilee",
    "systeme_production_electricite_origine_renouvelable",
    "type_batiment",
    "type_emetteur_installation_chauffage_n1",
    "type_emetteur_installation_chauffage_n2",
    "type_energie_climatisation",
    "type_energie_generateur_n1_ecs_n1",
    "type_energie_generateur_n1_installation_n1",
    "type_energie_generateur_n1_installation_n2",
    "type_energie_generateur_n2_ecs_n1",
    "type_energie_generateur_n2_installation_n1",
    "type_energie_generateur_n2_installation_n2",
    "type_energie_n1",
    "type_energie_n2",
    "type_energie_n3",
    "type_energie_principale_chauffage",
    "type_energie_principale_ecs",
    "type_generateur_chauffage_principal",
    "type_generateur_chauffage_principal_ecs",
    "type_generateur_froid",
    "type_generateur_n1_ecs_n1",
    "type_generateur_n1_installation_n1",
    "type_generateur_n1_installation_n2",
    "type_generateur_n2_ecs_n1",
    "type_generateur_n2_installation_n1",
    "type_generateur_n2_installation_n2",
    "type_installation_chauffage",
    "type_installation_chauffage_n1",
    "type_installation_chauffage_n2",
    "type_installation_ecs",
    "type_installation_ecs_n1",
    "type_installation_solaire_n1",
    "type_ventilation",
    "typologie_logement",
    "ubat_w_par_m2_k",
    "usage_generateur_n1_ecs_n1",
    "usage_generateur_n1_installation_n1",
    "usage_generateur_n1_installation_n2",
    "usage_generateur_n2_ecs_n1",
    "usage_generateur_n2_installation_n1",
    "usage_generateur_n2_installation_n2",
    "ventilation_posterieure_2012",
    "version_dpe",
    "volume_stockage_generateur_n1_ecs_n1",
    "volume_stockage_generateur_n2_ecs_n1",
    "zone_climatique",
]

# Mapping from JSON field names to database field names
JSON_TO_DB_FIELD_MAPPING = {
    "_geopoint": "_geopoint",
    "_i": "_i",
    "_id": "dpe_id",
    "_rand": "_rand",
    "_score": "_score",
    "adresse_ban": "adresse_ban",
    "adresse_brut": "adresse_brut",
    "annee_construction": "annee_construction",
    "appartement_non_visite": "appartement_non_visite",
    "apport_interne_saison_chauffe": "apport_interne_saison_chauffe",
    "apport_interne_saison_froide": "apport_interne_saison_froide",
    "apport_solaire_saison_chauffe": "apport_solaire_saison_chauffe",
    "apport_solaire_saison_froide": "apport_solaire_saison_froide",
    "besoin_chauffage": "besoin_chauffage",
    "besoin_ecs": "besoin_ecs",
    "besoin_refroidissement": "besoin_refroidissement",
    "categorie_enr": "categorie_enr",
    "classe_altitude": "classe_altitude",
    "classe_inertie_batiment": "classe_inertie_batiment",
    "code_departement_ban": "code_departement_ban",
    "code_insee_ban": "code_insee_ban",
    "code_postal_ban": "code_postal_ban",
    "code_postal_brut": "code_postal_brut",
    "code_region_ban": "code_region_ban",
    "complement_adresse_batiment": "complement_adresse_batiment",
    "complement_adresse_logement": "complement_adresse_logement",
    "configuration_installation_chauffage_n1": "configuration_installation_chauffage_n1",
    "configuration_installation_chauffage_n2": "configuration_installation_chauffage_n2",
    "configuration_installation_ecs_n1": "configuration_installation_ecs_n1",
    "conso_5_usages_ef": "conso_5_usages_ef",
    "conso_5_usages_ef_energie_n1": "conso_5_usages_ef_energie_n1",
    "conso_5_usages_ef_energie_n2": "conso_5_usages_ef_energie_n2",
    "conso_5_usages_ef_energie_n3": "conso_5_usages_ef_energie_n3",
    "conso_5_usages_ep": "conso_5_usages_ep",
    "conso_5_usages_par_m2_ef": "conso_5_usages_par_m2_ef",
    "conso_5_usages_par_m2_ep": "conso_5_usages_par_m2_ep",
    "conso_auxiliaires_ef": "conso_auxiliaires_ef",
    "conso_auxiliaires_ep": "conso_auxiliaires_ep",
    "conso_chauffage_ef": "conso_chauffage_ef",
    "conso_chauffage_ef_energie_n1": "conso_chauffage_ef_energie_n1",
    "conso_chauffage_ef_energie_n2": "conso_chauffage_ef_energie_n2",
    "conso_chauffage_ef_energie_n3": "conso_chauffage_ef_energie_n3",
    "conso_chauffage_ep": "conso_chauffage_ep",
    "conso_chauffage_generateur_n1_installation_n1": "conso_chauffage_generateur_n1_installation_n1",
    "conso_chauffage_generateur_n1_installation_n2": "conso_chauffage_generateur_n1_installation_n2",
    "conso_chauffage_generateur_n2_installation_n1": "conso_chauffage_generateur_n2_installation_n1",
    "conso_chauffage_generateur_n2_installation_n2": "conso_chauffage_generateur_n2_installation_n2",
    "conso_chauffage_installation_chauffage_n1": "conso_chauffage_installation_chauffage_n1",
    "conso_chauffage_installation_chauffage_n2": "conso_chauffage_installation_chauffage_n2",
    "conso_eclairage_ef": "conso_eclairage_ef",
    "conso_eclairage_ep": "conso_eclairage_ep",
    "conso_ecs_ef": "conso_ecs_ef",
    "conso_ecs_ef_energie_n1": "conso_ecs_ef_energie_n1",
    "conso_ecs_ef_energie_n2": "conso_ecs_ef_energie_n2",
    "conso_ecs_ef_energie_n3": "conso_ecs_ef_energie_n3",
    "conso_ecs_ep": "conso_ecs_ep",
    "conso_ef_generateur_n1_ecs_n1": "conso_ef_generateur_n1_ecs_n1",
    "conso_ef_generateur_n2_ecs_n1": "conso_ef_generateur_n2_ecs_n1",
    "conso_ef_installation_ecs_n1": "conso_ef_installation_ecs_n1",
    "conso_refroidissement_annuel": "conso_refroidissement_annuel",
    "conso_refroidissement_ef": "conso_refroidissement_ef",
    "conso_refroidissement_ep": "conso_refroidissement_ep",
    "coordonnee_cartographique_x_ban": "coordonnee_cartographique_x_ban",
    "coordonnee_cartographique_y_ban": "coordonnee_cartographique_y_ban",
    "cop_generateur_n1_ecs_n1": "cop_generateur_n1_ecs_n1",
    "cout_auxiliaires": "cout_auxiliaires",
    "cout_chauffage": "cout_chauffage",
    "cout_chauffage_energie_n1": "cout_chauffage_energie_n1",
    "cout_chauffage_energie_n2": "cout_chauffage_energie_n2",
    "cout_chauffage_energie_n3": "cout_chauffage_energie_n3",
    "cout_eclairage": "cout_eclairage",
    "cout_ecs": "cout_ecs",
    "cout_ecs_energie_n1": "cout_ecs_energie_n1",
    "cout_ecs_energie_n2": "cout_ecs_energie_n2",
    "cout_ecs_energie_n3": "cout_ecs_energie_n3",
    "cout_refroidissement": "cout_refroidissement",
    "cout_total_5_usages": "cout_total_5_usages",
    "cout_total_5_usages_energie_n1": "cout_total_5_usages_energie_n1",
    "cout_total_5_usages_energie_n2": "cout_total_5_usages_energie_n2",
    "cout_total_5_usages_energie_n3": "cout_total_5_usages_energie_n3",
    "date_derniere_modification_dpe": "date_derniere_modification_dpe",
    "date_etablissement_dpe": "date_etablissement_dpe",
    "date_fin_validite_dpe": "date_fin_validite_dpe",
    "date_installation_generateur_n1_ecs_n1": "date_installation_generateur_n1_ecs_n1",
    "date_installation_generateur_n2_ecs_n1": "date_installation_generateur_n2_ecs_n1",
    "date_reception_dpe": "date_reception_dpe",
    "date_visite_diagnostiqueur": "date_visite_diagnostiqueur",
    "deperditions_baies_vitrees": "deperditions_baies_vitrees",
    "deperditions_enveloppe": "deperditions_enveloppe",
    "deperditions_murs": "deperditions_murs",
    "deperditions_planchers_bas": "deperditions_planchers_bas",
    "deperditions_planchers_hauts": "deperditions_planchers_hauts",
    "deperditions_ponts_thermiques": "deperditions_ponts_thermiques",
    "deperditions_portes": "deperditions_portes",
    "deperditions_renouvellement_air": "deperditions_renouvellement_air",
    "description_generateur_chauffage_n1_installation_n1": "description_generateur_chauffage_n1_installation_n1",
    "description_generateur_chauffage_n1_installation_n2": "description_generateur_chauffage_n1_installation_n2",
    "description_generateur_chauffage_n2_installation_n1": "description_generateur_chauffage_n2_installation_n1",
    "description_generateur_chauffage_n2_installation_n2": "description_generateur_chauffage_n2_installation_n2",
    "description_generateur_froid": "description_generateur_froid",
    "description_generateur_n1_ecs_n1": "description_generateur_n1_ecs_n1",
    "description_generateur_n2_ecs_n1": "description_generateur_n2_ecs_n1",
    "description_installation_chauffage_n1": "description_installation_chauffage_n1",
    "description_installation_chauffage_n2": "description_installation_chauffage_n2",
    "description_installation_ecs_n1": "description_installation_ecs_n1",
    "electricite_pv_autoconsommee": "electricite_pv_autoconsommee",
    "emission_ges_5_usages": "emission_ges_5_usages",
    "emission_ges_5_usages_energie_n1": "emission_ges_5_usages_energie_n1",
    "emission_ges_5_usages_energie_n2": "emission_ges_5_usages_energie_n2",
    "emission_ges_5_usages_energie_n3": "emission_ges_5_usages_energie_n3",
    "emission_ges_5_usages_par_m2": "emission_ges_5_usages_par_m2",
    "emission_ges_auxiliaires": "emission_ges_auxiliaires",
    "emission_ges_chauffage": "emission_ges_chauffage",
    "emission_ges_chauffage_energie_n1": "emission_ges_chauffage_energie_n1",
    "emission_ges_chauffage_energie_n2": "emission_ges_chauffage_energie_n2",
    "emission_ges_chauffage_energie_n3": "emission_ges_chauffage_energie_n3",
    "emission_ges_eclairage": "emission_ges_eclairage",
    "emission_ges_ecs": "emission_ges_ecs",
    "emission_ges_ecs_energie_n1": "emission_ges_ecs_energie_n1",
    "emission_ges_ecs_energie_n2": "emission_ges_ecs_energie_n2",
    "emission_ges_ecs_energie_n3": "emission_ges_ecs_energie_n3",
    "emission_ges_refroidissement": "emission_ges_refroidissement",
    "etiquette_dpe": "etiquette_dpe",
    "etiquette_ges": "etiquette_ges",
    "facteur_couverture_solaire_installation_chauffage_n1": "facteur_couverture_solaire_installation_chauffage_n1",
    "facteur_couverture_solaire_n1": "facteur_couverture_solaire_n1",
    "facteur_couverture_solaire_saisi_installation_chauffage_n1": "facteur_couverture_solaire_saisi_installation_chauffage_n1",
    "facteur_couverture_solaire_saisi_n1": "facteur_couverture_solaire_saisi_n1",
    "hauteur_sous_plafond": "hauteur_sous_plafond",
    "identifiant_ban": "identifiant_ban",
    "indicateur_confort_ete": "indicateur_confort_ete",
    "inertie_lourde": "inertie_lourde",
    "isolation_toiture": "isolation_toiture",
    "logement_traversant": "logement_traversant",
    "methode_application_dpe": "methode_application_dpe",
    "modele_dpe": "modele_dpe",
    "nom_commune_ban": "nom_commune_ban",
    "nom_commune_brut": "nom_commune_brut",
    "nom_residence": "nom_residence",
    "nom_rue_ban": "nom_rue_ban",
    "nombre_appartement": "nombre_appartement",
    "nombre_logements_desservis_par_installation_ecs_n1": "nombre_logements_desservis_par_installation_ecs_n1",
    "nombre_module": "nombre_module",
    "nombre_niveau_immeuble": "nombre_niveau_immeuble",
    "nombre_niveau_logement": "nombre_niveau_logement",
    "numero_dpe": "numero_dpe",
    "numero_dpe_immeuble_associe": "numero_dpe_immeuble_associe",
    "numero_dpe_remplace": "numero_dpe_remplace",
    "numero_etage_appartement": "numero_etage_appartement",
    "numero_immatriculation_copropriete": "numero_immatriculation_copropriete",
    "numero_voie_ban": "numero_voie_ban",
    "periode_construction": "periode_construction",
    "periode_installation_generateur_froid": "periode_installation_generateur_froid",
    "position_logement_dans_immeuble": "position_logement_dans_immeuble",
    "presence_brasseur_air": "presence_brasseur_air",
    "presence_production_pv": "presence_production_pv",
    "production_ecs_solaire_installation_n1": "production_ecs_solaire_installation_n1",
    "production_electricite_pv_kwhep_par_an": "production_electricite_pv_kwhep_par_an",
    "protection_solaire_exterieure": "protection_solaire_exterieure",
    "qualite_isolation_enveloppe": "qualite_isolation_enveloppe",
    "qualite_isolation_menuiseries": "qualite_isolation_menuiseries",
    "qualite_isolation_murs": "qualite_isolation_murs",
    "qualite_isolation_plancher_bas": "qualite_isolation_plancher_bas",
    "qualite_isolation_plancher_haut_comble_amenage": "qualite_isolation_plancher_haut_comble_amenage",
    "qualite_isolation_plancher_haut_comble_perdu": "qualite_isolation_plancher_haut_comble_perdu",
    "qualite_isolation_plancher_haut_toit_terrasse": "qualite_isolation_plancher_haut_toit_terrasse",
    "score_ban": "score_ban",
    "statut_geocodage": "statut_geocodage",
    "surface_chauffee_installation_chauffage_n1": "surface_chauffee_installation_chauffage_n1",
    "surface_chauffee_installation_chauffage_n2": "surface_chauffee_installation_chauffage_n2",
    "surface_climatisee": "surface_climatisee",
    "surface_habitable_desservie_par_installation_ecs_n1": "surface_habitable_desservie_par_installation_ecs_n1",
    "surface_habitable_immeuble": "surface_habitable_immeuble",
    "surface_habitable_logement": "surface_habitable_logement",
    "surface_tertiaire_immeuble": "surface_tertiaire_immeuble",
    "surface_totale_capteurs_pv": "surface_totale_capteurs_pv",
    "surface_ventilee": "surface_ventilee",
    "systeme_production_electricite_origine_renouvelable": "systeme_production_electricite_origine_renouvelable",
    "type_batiment": "type_batiment",
    "type_emetteur_installation_chauffage_n1": "type_emetteur_installation_chauffage_n1",
    "type_emetteur_installation_chauffage_n2": "type_emetteur_installation_chauffage_n2",
    "type_energie_climatisation": "type_energie_climatisation",
    "type_energie_generateur_n1_ecs_n1": "type_energie_generateur_n1_ecs_n1",
    "type_energie_generateur_n1_installation_n1": "type_energie_generateur_n1_installation_n1",
    "type_energie_generateur_n1_installation_n2": "type_energie_generateur_n1_installation_n2",
    "type_energie_generateur_n2_ecs_n1": "type_energie_generateur_n2_ecs_n1",
    "type_energie_generateur_n2_installation_n1": "type_energie_generateur_n2_installation_n1",
    "type_energie_generateur_n2_installation_n2": "type_energie_generateur_n2_installation_n2",
    "type_energie_n1": "type_energie_n1",
    "type_energie_n2": "type_energie_n2",
    "type_energie_n3": "type_energie_n3",
    "type_energie_principale_chauffage": "type_energie_principale_chauffage",
    "type_energie_principale_ecs": "type_energie_principale_ecs",
    "type_generateur_chauffage_principal": "type_generateur_chauffage_principal",
    "type_generateur_chauffage_principal_ecs": "type_generateur_chauffage_principal_ecs",
    "type_generateur_froid": "type_generateur_froid",
    "type_generateur_n1_ecs_n1": "type_generateur_n1_ecs_n1",
    "type_generateur_n1_installation_n1": "type_generateur_n1_installation_n1",
    "type_generateur_n1_installation_n2": "type_generateur_n1_installation_n2",
    "type_generateur_n2_ecs_n1": "type_generateur_n2_ecs_n1",
    "type_generateur_n2_installation_n1": "type_generateur_n2_installation_n1",
    "type_generateur_n2_installation_n2": "type_generateur_n2_installation_n2",
    "type_installation_chauffage": "type_installation_chauffage",
    "type_installation_chauffage_n1": "type_installation_chauffage_n1",
    "type_installation_chauffage_n2": "type_installation_chauffage_n2",
    "type_installation_ecs": "type_installation_ecs",
    "type_installation_ecs_n1": "type_installation_ecs_n1",
    "type_installation_solaire_n1": "type_installation_solaire_n1",
    "type_ventilation": "type_ventilation",
    "typologie_logement": "typologie_logement",
    "ubat_w_par_m2_k": "ubat_w_par_m2_k",
    "usage_generateur_n1_ecs_n1": "usage_generateur_n1_ecs_n1",
    "usage_generateur_n1_installation_n1": "usage_generateur_n1_installation_n1",
    "usage_generateur_n1_installation_n2": "usage_generateur_n1_installation_n2",
    "usage_generateur_n2_ecs_n1": "usage_generateur_n2_ecs_n1",
    "usage_generateur_n2_installation_n1": "usage_generateur_n2_installation_n1",
    "usage_generateur_n2_installation_n2": "usage_generateur_n2_installation_n2",
    "ventilation_posterieure_2012": "ventilation_posterieure_2012",
    "version_dpe": "version_dpe",
    "volume_stockage_generateur_n1_ecs_n1": "volume_stockage_generateur_n1_ecs_n1",
    "volume_stockage_generateur_n2_ecs_n1": "volume_stockage_generateur_n2_ecs_n1",
    "zone_climatique": "zone_climatique",
}
