duckdb_profile:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "database_name.duckdb"
      extensions:
        - httpfs
        - parquet
        - spatial
      attach:
        - path: production.duckdb

    prod:
      type: duckdb
      path: "md:dwh?motherduck_token={{env_var('MD_TOKEN')}}"
      extensions:
        - httpfs
        - parquet
        - s3
        - spatial