duckdb_profile:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "database_name.duckdb"
      extensions:
        - httpfs
        - parquet
        - s3
        - spatial
      settings:
        s3_endpoint: "{{ env_var('S3_ENDPOINT_URL') }}" 
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}" 
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}" 
      attach:
        - path: production.duckdb

    prod:
      type: duckdb
      path: "/opt/dagster/dagster_home/db/dagster.duckdb"
      extensions:
        - httpfs
        - parquet
        - s3
        - spatial