snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_DBT_USER') }}"
      password: "{{ env_var('SNOWFLAKE_DBT_PASSWORD') }}" 

      role: DBT_ROLE
      database: "{{ env_var('SNOWFLAKE_DBT_DB') }}" 
      warehouse: "{{ env_var('SNOWFLAKE_DBT_WH') }}" 
      schema: PUBLIC
      threads: 1
      client_session_keep_alive: False

      connect_retries: 0 
      connect_timeout: 10
      retry_on_database_errors: False 
      retry_all: False
      reuse_connections: False
duckdb_profile:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "database_name.duckdb"
      extensions:
        - httpfs
        - parquet
        - s3
      settings:
        s3_endpoint: "{{ env_var('S3_ENDPOINT_URL') }}" 
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}" 
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}" 
      attach:
        - path: production.duckdb