services:
  db:
    image: postgis/postgis:14-3.3
    container_name: zlv
    restart: always
    shm_size: 1g
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ../server/src/infra/database:/database:ro
  adminer:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - "8080:8080"
  mail:
    image: maildev/maildev:2.0.5
    container_name: mail
    ports:
      - "1025:1025"
      - "1080:1080"
  s3:
    image: adobe/s3mock:3.5.2
    container_name: s3
    environment:
      initialBuckets: "zerologementvacant"
    ports:
      - "9090:9090"
      - "9191:9191"
  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  data:
    driver: local
    name: zlv-db
  redis_data:
    driver: local
  es_data:
      driver: local
