/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BanAddresses {
  /**
   * The full street address
   */
  address: string;
  addressKind: string;
  /**
   * The identifier returned by the BAN API
   */
  banId: string | null;
  /**
   * Deprecated in favor of address
   */
  city: string | null;
  cityCode: string | null;
  /**
   * Deprecated in favor of address
   */
  houseNumber: string | null;
  lastUpdatedAt: Timestamp | null;
  latitude: number | null;
  longitude: number | null;
  /**
   * Deprecated in favor of address
   */
  postalCode: string | null;
  refId: string;
  score: number | null;
  /**
   * Deprecated in favor of address
   */
  street: string | null;
}

export interface Buildings {
  classDpe: string | null;
  classGes: string | null;
  dpeDateAt: Timestamp | null;
  dpeId: string | null;
  dpeImportMatch: string | null;
  dpeType: string | null;
  heatingBuilding: string | null;
  housingCount: number;
  id: string;
  rentHousingCount: number | null;
  rnbId: string | null;
  rnbIdScore: number | null;
  vacantHousingCount: number;
}

export interface CampaignEvents {
  campaignId: string;
  eventId: string;
}

export interface CampaignHousingEvents {
  campaignId: string | null;
  eventId: string;
  housingGeoCode: string;
  housingId: string;
}

export interface Campaigns {
  archivedAt: Timestamp | null;
  campaignNumberDeprecated: number | null;
  confirmedAt: Timestamp | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  establishmentId: string;
  exportedAt: Timestamp | null;
  file: string | null;
  filters: Json | null;
  /**
   * The group from which the campaign was created, if any
   */
  groupId: string | null;
  housingCount: Generated<number>;
  id: Generated<string>;
  kindDeprecated: Generated<number | null>;
  ownerCount: Generated<number>;
  recoveryId: string | null;
  reminderNumberDeprecated: number | null;
  returnCount: Generated<number>;
  returnRate: Generated<number | null>;
  sentAt: Timestamp | null;
  startMonthDeprecated: string | null;
  status: string;
  title: string;
  userId: string;
  validatedAt: Timestamp | null;
}

export interface CampaignsDrafts {
  campaignId: string;
  draftId: string;
}

export interface CampaignsHousing {
  advice: string | null;
  campaignId: string;
  housingGeoCode: string;
  housingId: string;
}

export interface ContactPoints {
  address: string | null;
  email: string | null;
  establishmentId: string;
  geoCodes: string[];
  id: Generated<string>;
  notes: string | null;
  opening: string | null;
  phone: string | null;
  title: string;
}

export interface DfHousingNat2024 {
  assieft: string | null;
  banCp: string | null;
  banGeom: string | null;
  banId: string | null;
  banScore: Numeric | null;
  banType: string | null;
  catpro2: string | null;
  catpro2txt: string | null;
  catpro3: string | null;
  catproges2: string | null;
  catpropro2: string | null;
  cbtabt: string | null;
  cc48lc: string | null;
  cchpr: string | null;
  ccocif: string | null;
  ccocom: string | null;
  ccodep: string | null;
  ccodir: string | null;
  ccoeva: string | null;
  ccoevatxt: string | null;
  ccoifp: number | null;
  cconac: string | null;
  cconactxt: string | null;
  cconlc: string | null;
  cconlctxt: string | null;
  ccoplc: string | null;
  ccoplctxt: string | null;
  ccopre: string | null;
  ccoriv: string | null;
  ccosec: string | null;
  ccovoi: string | null;
  ccpper: string | null;
  ccthp: string | null;
  cleinvar: string | null;
  codique: string | null;
  ctpdl: string | null;
  dcomrd: string | null;
  descc: string | null;
  dindic: string | null;
  disBanFf: number | null;
  dloy48a: number | null;
  dnatcg: string | null;
  dnatlc: string | null;
  dnbniv: string | null;
  dniv: string | null;
  dnubat: string | null;
  dnufnl: string | null;
  dnupla: string | null;
  dnupro: string | null;
  dnvoiri: string | null;
  dpor: string | null;
  dteloc: string | null;
  dteloctxt: string | null;
  dvltrt: number | null;
  dvoilib: string | null;
  fburx: number | null;
  geomloc: string | null;
  geomrnb: string | null;
  gimtom: string | null;
  gpdl: string | null;
  gtauom: string | null;
  hlmsem: string | null;
  idbat: string | null;
  idcom: string | null;
  idcomtxt: string | null;
  idlocal: string | null;
  idpar: string | null;
  idpk: number | null;
  idprocpte: string | null;
  idsec: string | null;
  idtup: string | null;
  idvoie: string | null;
  invar: string | null;
  janbilmin: number | null;
  jannat: string | null;
  jannath: string | null;
  jdatat: string | null;
  jdatatan: string | null;
  jdatatv: string | null;
  jdatcgl: string | null;
  jdbabt: string | null;
  jrtabt: string | null;
  locprop: string | null;
  locproptxt: string | null;
  logh: boolean | null;
  loghappt: boolean | null;
  loghlls: string | null;
  loghmais: boolean | null;
  loghvac: string | null;
  loghvac2a: boolean | null;
  loghvac5a: boolean | null;
  loghvacdeb: string | null;
  nbagrement: number | null;
  nbannexe: number | null;
  nbetagemax: number | null;
  nbgarpark: number | null;
  nbnivssol: number | null;
  nbpiscine: number | null;
  nbterrasse: number | null;
  ndroit: number | null;
  ndroitges: number | null;
  ndroitindi: number | null;
  ndroitpro: number | null;
  npevd: number | null;
  npevp: number | null;
  npevph: number | null;
  npevtot: number | null;
  npieceFf: number | null;
  npieceI: number | null;
  npieceP2: number | null;
  npieceSoc: number | null;
  postel: string | null;
  rnbId: string | null;
  rnbIdScore: string | null;
  rppoRs: string | null;
  slocal: number | null;
  sourceGeo: string | null;
  sparkncp: number | null;
  sparkp: number | null;
  sprincp: number | null;
  ssecncp: number | null;
  ssecp: number | null;
  stotd: number | null;
  stotdsueic: number | null;
  stoth: number | null;
  top48a: string | null;
  toprev: string | null;
  typeact: string | null;
  typeloc: string | null;
  vecteur: string | null;
}

export interface DfOwnersNat2024 {
  catpro2: string | null;
  catpro2txt: string | null;
  catpro3: string | null;
  catpro3txt: string | null;
  ccocif: string | null;
  ccocom: string | null;
  ccocomadr: string | null;
  ccodem: string | null;
  ccodemtxt: string | null;
  ccodep: string | null;
  ccodep1a2: string | null;
  ccodir: string | null;
  ccodira: string | null;
  ccodro: string | null;
  ccodrotxt: string | null;
  ccogrm: string | null;
  ccogrmtxt: string | null;
  ccopay: string | null;
  ccopos: string | null;
  ccoqua: string | null;
  ccoriv: string | null;
  ccovoi: string | null;
  datja: string | null;
  ddenom: string | null;
  dforme: string | null;
  dformjur: string | null;
  dindic: string | null;
  dldnss: string | null;
  dlign3: string | null;
  dlign4: string | null;
  dlign5: string | null;
  dlign6: string | null;
  dnatpr: string | null;
  dnatprtxt: string | null;
  dnomlp: string | null;
  dnomus: string | null;
  dnulp: string | null;
  dnuper: string | null;
  dnupro: string | null;
  dnvoiri: string | null;
  dprnlp: string | null;
  dprnus: string | null;
  dqualp: string | null;
  dsglpm: string | null;
  dsiren: string | null;
  gdesip: string | null;
  gtoper: string | null;
  gtyp3: string | null;
  gtyp4: string | null;
  gtyp5: string | null;
  gtyp6: string | null;
  idcom: string | null;
  idcomtxt: string | null;
  idpersonne: string | null;
  idpk: number | null;
  idprocpte: string | null;
  idprodroit: string | null;
  idvoie: string | null;
  jdatnss: string | null;
  locprop: string | null;
  locproptxt: string | null;
  topja: string | null;
  typedroit: string | null;
}

export interface DocumentEvents {
  documentId: string;
  eventId: string;
}

export interface Documents {
  contentType: string;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  deletedAt: Timestamp | null;
  establishmentId: string;
  filename: string;
  id: string;
  s3Key: string;
  sizeBytes: number;
  updatedAt: Timestamp | null;
}

export interface DocumentsHousings {
  documentId: string;
  housingGeoCode: string;
  housingId: string;
}

export interface Drafts {
  body: string | null;
  createdAt: Timestamp;
  /**
   * The establishment to which the draft belongs
   */
  establishmentId: string;
  id: string;
  logo: string[] | null;
  logoNextOne: string | null;
  logoNextTwo: string | null;
  senderId: string | null;
  subject: string | null;
  updatedAt: Timestamp;
  writtenAt: string | null;
  writtenFrom: string | null;
}

export interface Establishments {
  available: boolean;
  deletedAt: Timestamp | null;
  depCode: string[] | null;
  depName: string | null;
  id: Generated<string>;
  kind: string;
  kindAdmin: string | null;
  kindAdminMeta: string | null;
  layerGeoLabel: string | null;
  localitiesGeoCode: string[] | null;
  millesime: string | null;
  name: string;
  regCode: string[] | null;
  regName: string | null;
  siren: number | null;
  siret: string | null;
  source: Generated<string>;
  suspendedAt: Timestamp | null;
  suspendedCause: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface EstablishmentsLocalities {
  establishmentId: string;
  localityId: string;
}

export interface Events {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  id: Generated<string>;
  /**
   * The value after this event
   */
  nextNew: Json | null;
  /**
   * The value before this event
   */
  nextOld: Json | null;
  /**
   * The type of the event, for example "housing:created"
   */
  type: Generated<string>;
}

export interface FastHousing {
  actualDpe: string | null;
  addressDgfip: string[];
  beneficiaryCount: number | null;
  buildingGroupId: string | null;
  buildingId: string | null;
  buildingLocation: string | null;
  buildingYear: number | null;
  cadastralClassification: number | null;
  cadastralReference: string | null;
  condominium: string | null;
  dataFileYears: string[] | null;
  dataSource: string | null;
  dataYears: number[];
  energyConsumptionAtBdnb: Timestamp | null;
  energyConsumptionBdnb: string | null;
  geoCode: string;
  geolocation: string | null;
  housingKind: string;
  id: string;
  invariant: string;
  lastMutationDate: Timestamp | null;
  lastMutationType: Generated<string | null>;
  lastTransactionDate: Timestamp | null;
  lastTransactionValue: number | null;
  latitudeDgfip: number | null;
  livingArea: number | null;
  localId: string;
  longitudeDgfip: number | null;
  mutationDate: Timestamp | null;
  occupancy: string;
  occupancyHistory: string | null;
  occupancyIntended: string | null;
  occupancySource: string;
  plotArea: number | null;
  plotId: string | null;
  rentalValue: number | null;
  roomsCount: number | null;
  status: number;
  subStatus: string | null;
  taxed: boolean | null;
  uncomfortable: boolean;
  vacancyStartYear: number | null;
}

export interface GeographyColumns {
  coordDimension: number | null;
  fGeographyColumn: string | null;
  fTableCatalog: string | null;
  fTableName: string | null;
  fTableSchema: string | null;
  srid: number | null;
  type: string | null;
}

export interface GeometryColumns {
  coordDimension: number | null;
  fGeometryColumn: string | null;
  fTableCatalog: string | null;
  fTableName: string | null;
  fTableSchema: string | null;
  srid: number | null;
  type: string | null;
}

export interface GeoPerimeters {
  createdAt: Generated<Timestamp | null>;
  createdBy: string | null;
  establishmentId: string | null;
  geom: string | null;
  id: Generated<string>;
  kind: string | null;
  name: string | null;
}

export interface GroupHousingEvents {
  eventId: string;
  groupId: string | null;
  housingGeoCode: string;
  housingId: string;
}

export interface Groups {
  archivedAt: Timestamp | null;
  createdAt: Timestamp;
  description: string;
  establishmentId: string;
  exportedAt: Timestamp | null;
  housingCount: Generated<number>;
  id: string;
  ownerCount: Generated<number>;
  title: string;
  /**
   * The creator id
   */
  userId: string;
}

export interface GroupsHousing {
  groupId: string;
  housingGeoCode: string;
  housingId: string;
}

export interface HousingDocumentEvents {
  documentId: string;
  eventId: string;
  housingGeoCode: string;
  housingId: string;
}

export interface HousingEvents {
  eventId: string;
  housingGeoCode: string;
  housingId: string;
}

export interface HousingNotes {
  housingGeoCode: string;
  housingId: string;
  noteId: string;
}

export interface HousingOwnerEvents {
  eventId: string;
  housingGeoCode: string;
  housingId: string;
  ownerId: string | null;
}

export interface HousingPrecisions {
  createdAt: Generated<Timestamp>;
  housingGeoCode: string;
  housingId: string;
  precisionId: string;
}

export interface KnexMigrations {
  batch: number | null;
  id: Generated<number>;
  migrationTime: Timestamp | null;
  name: string | null;
}

export interface KnexMigrationsLock {
  index: Generated<number>;
  isLocked: number | null;
}

export interface Localities {
  geoCode: string;
  id: Generated<string>;
  localityKind: string | null;
  name: string;
  taxKind: Generated<string>;
  taxRate: number | null;
}

export interface Notes {
  contactKindDeprecated: string | null;
  content: string;
  createdAt: Generated<Timestamp | null>;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  noteKind: Generated<string>;
  titleDeprecated: string | null;
  updatedAt: Timestamp | null;
}

export interface OwnerEvents {
  eventId: string;
  ownerId: string;
}

export interface OwnerMatches {
  idpersonne: string;
  ownerId: string;
}

export interface OwnerNotes {
  noteId: string;
  ownerId: string;
}

export interface Owners {
  additionalAddress: string | null;
  addressDgfip: string[] | null;
  administrator: string | null;
  birthDate: Timestamp | null;
  createdAt: Timestamp | null;
  dataSource: string | null;
  email: string | null;
  entity: string | null;
  fullName: string;
  fullNameFts: Generated<string | null>;
  id: Generated<string>;
  /**
   * L’identifiant communal provenant de LOVAC
   */
  idpersonne: string | null;
  kindClass: string | null;
  phone: string | null;
  siren: string | null;
  updatedAt: Timestamp | null;
}

export interface OwnersDept {
  ownerId: string;
  ownerIdpersonne: string;
}

export interface OwnersDuplicates {
  administrator: string | null;
  birthDate: Timestamp | null;
  email: string | null;
  fullName: string;
  id: Generated<string>;
  ownerKind: string | null;
  ownerKindDetail: string | null;
  phone: string | null;
  rawAddress: string[];
  sourceId: string;
}

export interface OwnersHousing {
  endDate: Timestamp | null;
  housingGeoCode: string;
  housingId: string;
  idprocpte: string | null;
  idprodroit: string | null;
  locpropDistanceBan: number | null;
  locpropRelativeBan: number | null;
  locpropSource: string | null;
  origin: string | null;
  ownerId: string;
  propertyRight: string | null;
  rank: number | null;
  startDate: Timestamp | null;
}

export interface PrecisionHousingEvents {
  eventId: string;
  housingGeoCode: string;
  housingId: string;
  precisionId: string | null;
}

export interface Precisions {
  category: string;
  id: string;
  label: string;
  order: number;
}

export interface Prospects {
  email: string;
  establishmentSiren: number | null;
  hasAccount: Generated<boolean>;
  hasCommitment: Generated<boolean>;
  lastAccountRequestAt: Timestamp;
}

export interface ResetLinks {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  usedAt: Timestamp | null;
  userId: string;
}

export interface Senders {
  address: string | null;
  createdAt: Timestamp;
  email: string | null;
  establishmentId: string;
  firstName: string | null;
  id: string;
  lastName: string | null;
  name: string | null;
  phone: string | null;
  service: string | null;
  signatoryOneDocumentId: string | null;
  signatoryOneFile: string | null;
  signatoryOneFirstName: string | null;
  signatoryOneLastName: string | null;
  signatoryOneRole: string | null;
  signatoryTwoDocumentId: string | null;
  signatoryTwoFile: string | null;
  signatoryTwoFirstName: string | null;
  signatoryTwoLastName: string | null;
  signatoryTwoRole: string | null;
  updatedAt: Timestamp;
}

export interface Settings {
  establishmentId: string | null;
  id: string;
  inboxEnabled: Generated<boolean | null>;
}

export interface SignupLinks {
  expiresAt: Timestamp;
  id: string;
  prospectEmail: string;
}

export interface SpatialRefSys {
  authName: string | null;
  authSrid: number | null;
  proj4text: string | null;
  srid: number;
  srtext: string | null;
}

export interface UserPerimeters {
  departments: Generated<string[]>;
  epci: Generated<string[]>;
  frEntiere: Generated<boolean>;
  geoCodes: Generated<string[]>;
  regions: Generated<string[]>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Users {
  activatedAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  email: string;
  establishmentId: string | null;
  firstName: string | null;
  id: Generated<string>;
  kind: string | null;
  lastAuthenticatedAt: Timestamp | null;
  lastName: string | null;
  password: string | null;
  phone: string | null;
  position: string | null;
  role: number;
  suspendedAt: Timestamp | null;
  suspendedCause: string | null;
  timePerWeek: string | null;
  twoFactorCode: string | null;
  twoFactorCodeGeneratedAt: Timestamp | null;
  twoFactorEnabledAt: Timestamp | null;
  twoFactorFailedAttempts: Generated<number>;
  twoFactorLockedUntil: Timestamp | null;
  twoFactorSecret: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface UsersEstablishments {
  createdAt: Generated<Timestamp>;
  establishmentId: string;
  establishmentSiren: string;
  hasCommitment: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface DB {
  banAddresses: BanAddresses;
  buildings: Buildings;
  campaignEvents: CampaignEvents;
  campaignHousingEvents: CampaignHousingEvents;
  campaigns: Campaigns;
  campaignsDrafts: CampaignsDrafts;
  campaignsHousing: CampaignsHousing;
  contactPoints: ContactPoints;
  dfHousingNat2024: DfHousingNat2024;
  dfOwnersNat2024: DfOwnersNat2024;
  documentEvents: DocumentEvents;
  documents: Documents;
  documentsHousings: DocumentsHousings;
  drafts: Drafts;
  establishments: Establishments;
  establishmentsLocalities: EstablishmentsLocalities;
  events: Events;
  fastHousing: FastHousing;
  geographyColumns: GeographyColumns;
  geometryColumns: GeometryColumns;
  geoPerimeters: GeoPerimeters;
  groupHousingEvents: GroupHousingEvents;
  groups: Groups;
  groupsHousing: GroupsHousing;
  housingDocumentEvents: HousingDocumentEvents;
  housingEvents: HousingEvents;
  housingNotes: HousingNotes;
  housingOwnerEvents: HousingOwnerEvents;
  housingPrecisions: HousingPrecisions;
  knexMigrations: KnexMigrations;
  knexMigrationsLock: KnexMigrationsLock;
  localities: Localities;
  notes: Notes;
  ownerEvents: OwnerEvents;
  ownerMatches: OwnerMatches;
  ownerNotes: OwnerNotes;
  owners: Owners;
  ownersDept: OwnersDept;
  ownersDuplicates: OwnersDuplicates;
  ownersHousing: OwnersHousing;
  precisionHousingEvents: PrecisionHousingEvents;
  precisions: Precisions;
  prospects: Prospects;
  resetLinks: ResetLinks;
  senders: Senders;
  settings: Settings;
  signupLinks: SignupLinks;
  spatialRefSys: SpatialRefSys;
  userPerimeters: UserPerimeters;
  users: Users;
  usersEstablishments: UsersEstablishments;
}
