name: Deploy to Clever Cloud

on:
  workflow_run:
    workflows: [Node.js CI]
    types: [completed]
    branches:
      - ci-deploy-on-clever-cloud

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install clever-tools
        run: npm install -g clever-tools

      - name: Deploy to Clever Cloud
        env:
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          ORGA_ID: ${{ secrets.CLEVER_ORG }}
        run: |
          clever deploy --alias front-staging
          clever deploy --alias api-staging
          clever deploy --alias queue-staging
