name: End-to-end tests

on:
  push:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable Corepack
        run: corepack enable

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_API: ${{ secrets.API_HOST }}
          CYPRESS_BASE_URL: ${{ secrets.HOST }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
        with:
          working-directory: e2e
          build: false
          start: yarn cypress run
