name: Data Stack CI

on:
  push:
    paths:
      - analytics/**

jobs:
  deploy-dagster:
    uses: ./.github/workflows/deploy.yml
    with:
      app: dagster-production
      branch: main
    secrets: inherit

  deploy-metabase:
    uses: ./.github/workflows/deploy.yml
    with:
      app: metabase-production
      branch: main
    secrets: inherit
