name: Data Stack CI

on:
  push:

jobs:
  deploy-dagster:
    uses: ./.github/workflows/deploy.yml
    with:
      app: Dagster (Production)
      alias: dagster-production
      branch: feat/data-*
    secrets: inherit

  deploy-metabase:
    uses: ./.github/workflows/deploy.yml
    with:
      app: Production - Metabase
      alias: metabase-production
      branch: feat/data-*
    secrets: inherit
